/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post98, git sha1 a1bb0255d) */

module simplecounter(clk, counter, enable);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire [10:0] \$1 ;
  reg [9:0] \$2 ;
  input clk;
  wire clk;
  output [9:0] counter;
  reg [9:0] counter = 10'h000;
  input enable;
  wire enable;
  assign \$1  = counter + 1'h1;
  always @(posedge clk)
    counter <= \$2 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$2  = counter;
    if (enable) begin
      \$2  = \$1 [9:0];
    end
  end
endmodule

